/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ArcanaI, ArcanaIInterface } from "../ArcanaI";

const _abi = [
  {
    inputs: [],
    name: "aggregateLogin",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "appId",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "appName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "store",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "bandwidth",
        type: "uint256",
      },
    ],
    name: "setAppLevelLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "store",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "bandwidth",
        type: "uint256",
      },
    ],
    name: "setDefaultLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ArcanaI__factory {
  static readonly abi = _abi;
  static createInterface(): ArcanaIInterface {
    return new utils.Interface(_abi) as ArcanaIInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ArcanaI {
    return new Contract(address, _abi, signerOrProvider) as ArcanaI;
  }
}
