/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ArcanaI, ArcanaIInterface } from "../ArcanaI";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "store",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "bandwidth",
        type: "uint256",
      },
    ],
    name: "setAppLevelLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ArcanaI__factory {
  static readonly abi = _abi;
  static createInterface(): ArcanaIInterface {
    return new utils.Interface(_abi) as ArcanaIInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ArcanaI {
    return new Contract(address, _abi, signerOrProvider) as ArcanaI;
  }
}
